version: "3"

tasks:
  stop:
    cmds:
      - docker-compose --profile all rm -sf
  
  start-dev:
    cmds: 
      - docker-compose --profile dev up --build
      - defer: {task: stop}

  setup-test:
    cmds: 
      - docker-compose --profile test up --build -d

  pretty:
    cmds:
      - go fmt ./...
      - go mod tidy
      - go clean
  
  validate:
    cmds: 
      - golangci-lint run --trace-path trace.out --cpu-profile-path cpu.out --mem-profile-path mem.out
  
  test:
    deps: [setup-test]
    cmds:
      - go test -v -cover ./...
      - defer: {task: stop}

  build:
    cmds:
      - go build -race -o main.out cmd/service/main.go
  
  run:
    cmds:
      - go run cmd/service/main.go